stages:
  - npm_install
  - es_lint
  - run_app
  - curl

module_install:
  stage: npm_install
  image: node
  script:
    - npm install

eslint:
  stage: es_lint
  image: node
  script:
    - npm install
    - npx eslint ./src/components/Home.js --fix


run_app:
  stage: run_app
  image: node
  script: 
    - npm install
    - npm run build

curl:
  stage: curl
  script:
    - echo "GET"
    - curl -X GET https://api.valentincarrichon.fr/sports
    - echo "PUT"
    - curl -X PUT -d "name=test&description=testdescr" https://api.valentincarrichon.fr/sports/7
    - echo "DELETE"
    - curl -X DELETE https://api.valentincarrichon.fr/sports/12
    - echo "POST"
    - curl -X POST -d "name=test&description=testdescr" https://api.valentincarrichon.fr/sports

