stages:
  # - npm_install
  # - es_lint
  - run_app
  # - curl

# module_install:
#   stage: npm_install
#   image: node
#   script:
#     - npm install

# eslint:
#   stage: es_lint
#   image: node
#   script:
#     - npm install
#     - npx eslint ./src/components/Home.js --fix



run_app:
  stage: run_app
  image: node
  variables:
    - CI_SERVER_URL="http://localhost"
    - CI_SERVER_HOST="localhost"
  script: 
    - npm install
    - npm install pm2 -g
    - pm2 start ./node_modules/react-scripts/scripts/start.js --name "REACT"
    - curl CI_SERVER_HOST:3000

# curl:
#   stage: curl
#   image: debian
#   script:
#     - curl -i -H "Accept:application/json" -H "Content-Type:application/json" -X GET http://localhost:3001/users/testPipeline

