stages:
  - npm_install
  - es_lint
  - run_app
  - curl
  - container_registry

module_install:
  stage: npm_install
  image: node
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
  # only:
  #   changes:
  #     - "package.json"

eslint:
  stage: es_lint
  image: node 
  dependencies:
    - module_install
  script:
    - npx eslint ./src/components/Home.js --fix

run_app:
  stage: run_app
  image: node
  dependencies:
    - module_install
  script: 
    - npm run build
    - nohup npm start &

curl:
  stage: curl
  script:
    - echo "GET"
    - curl -X GET https://api.valentincarrichon.fr/sports
    - echo "PUT"
    - curl -X PUT -d "name=test&description=testdescr" https://api.valentincarrichon.fr/sports/7
    - echo "DELETE"
    - curl -X DELETE https://api.valentincarrichon.fr/sports/12
    - echo "POST"
    - curl -X POST -d "name=test&description=testdescr" https://api.valentincarrichon.fr/sports

build_image:
  stage: container_registry
  image: docker:git
  when: on_success
  services:
    - docker:dind
  script:
    - docker login registry.gitlab.com
    - docker build -t registry.gitlab.com/carrichonval/tp_pipeline .
    - docker push registry.gitlab.com/carrichonval/tp_pipeline
  only:
    - master


